### ISSUE TITLE
Admin - Remove the default from the build which is not included in the implementation.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Prestige-Pump-Rentals#123]
![image](https://cloud.githubusercontent.com/assets/13363508/15771058/b656f100-299a-11e6-8f38-b24ecf6e79ed.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15771085/e1ea2fda-299a-11e6-8852-95dc2d678024.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15771104/ff4452b8-299a-11e6-943e-6709a5d58ecb.png)

**Comment by maehtitan** [comment]
@cyril-7175N Still there is a Gallery custom post

**Comment by cyril-7175N** [comment]
@maehtitan FYI Gallery is not a custom post. Rather it's an Options page. Anyway it's now removed.
