### ISSUE TITLE
Banner Section: How Can We Help and Watch Video aren't implemented.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Prestige-Pump-Rentals#14]
![image](https://cloud.githubusercontent.com/assets/13363508/15644061/429b4ff0-2683-11e6-9953-e6a04dacabe4.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15644074/55fea1dc-2683-11e6-9551-8b2b4a8f20f6.png)

**Comment by cyril-7175N** [comment]
How Can We Help and Watch Video moved to theme options page under "Global Banner Links" tab.
