### ISSUE TITLE
Equipment: - Responsive View: Images are too stretched in 991px and below viewport sizes

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Prestige-Pump-Rentals#158]
![image](https://cloud.githubusercontent.com/assets/13363508/16139074/b09e5d34-3476-11e6-90a3-fee8c2a6c263.png)
![image](https://cloud.githubusercontent.com/assets/13363508/16139090/dceda8ae-3476-11e6-92ce-2afea5d35d0f.png)

**Comment by cyril-7175N** [comment]
Note: Some posts' featured image currently have low image resolution causing to display blurry.
