### ISSUE TITLE
Homepage - The MDW Group: Removing the Visit button text label, removed all the logo as well. Only the button must be removed not including the logo.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Prestige-Pump-Rentals#170]
![image](https://cloud.githubusercontent.com/assets/13363508/16142555/d8c4da14-3498-11e6-80fe-a40eea36fdbc.png)

**Comment by cyril-7175N** [comment]
Removing the Visit button text label will now remove the button. The logos are now clickable.
