### ISSUE TITLE
Homepage - Follow Us On: Is the Youtube icon supposed to be redirected to the Channel and not the specific video?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Prestige-Pump-Rentals#48]
![image](https://cloud.githubusercontent.com/assets/13363508/15731740/ecb7cae0-28a9-11e6-972e-09273af0c3e5.png)

![image](https://cloud.githubusercontent.com/assets/13363508/15731666/7578706a-28a9-11e6-9792-5923b66200e9.png)

**Comment by cyril-7175N** [comment]
Currently the live site have NO available youtube channel link. Consider to be removed from the front-end. Watch video link already implemented on the banner area.
