### ISSUE TITLE
Admin - Business Details: Is the Perth carins included in the implementation?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Prestige-Pump-Rentals#63]
**Coz it is not showing in the front-end.**
![image](https://cloud.githubusercontent.com/assets/13363508/15734704/035878b0-28c5-11e6-901f-6dff435fa704.png)

**Comment by cyril-7175N** [comment]
I Guess the PM have just renamed the "Carins" Business details to "Wedgefield". Not a bug anymore as it is already displayed on the front-end.

**Comment by maehtitan** [comment]
@cyril-7175N The Perth Carins that has been change to Wedgefield Office isn't showing in the front-end.

**Comment by cyril-7175N** [comment]
Contact details from the business details are now displayed on the "Contact Us" page.
Control all the content through CMS under Business Details Settings. 
http://prestigepumprentals-imp.stage.titanweb.com.au/wp-admin/admin.php?page=titan-business-details
