### ISSUE TITLE
Homepage: Text link isn't styled according to the design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/MDW-Prestige-Pump-Rentals#97]
![image](https://cloud.githubusercontent.com/assets/13363508/15740085/dc62b434-28e5-11e6-9aab-5810c2e64780.png)

**Comment by maehtitan** [comment]
Still white color you cannot identify if it is a text link.

**Comment by cyril-7175N** [comment]
Text link changed to yellow.
